### ISSUE TITLE
Unable to build.

### ISSUE THREAD

**Issue by EggzyGallahad** [WryOpussum/sm64LinuxBuilder#4]
I installed all the dependencies. Ubuntu 22.04

./sm64LinuxBuilder.bin
Traceback (most recent call last):
File "main.py", line 20, in <module>
gi.require_version('Gtk', '4.0')
File "gi/__init__.py", line 129, in require_version
ValueError: Namespace Gtk not available for version 4.0
[1430443] Failed to execute script 'main' due to unhandled exception!

sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-4.0 build-essential git python3 libglew-dev libsdl2-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
libglew-dev is already the newest version (2.2.0-4).
gir1.2-gtk-4.0 is already the newest version (4.6.9+ds-0ubuntu0.22.04.2).
git is already the newest version (1:2.34.1-1ubuntu1.10).
python3 is already the newest version (3.10.6-1~22.04).
python3-gi is already the newest version (3.42.1-0ubuntu1).
python3-gi-cairo is already the newest version (3.42.1-0ubuntu1).
libsdl2-dev is already the newest version (2.0.20+dfsg-2ubuntu1.22.04.1).

**Comment by nexussapphire** [comment]
At the very beginning of the main.py file, if you put `#!/usr/bin/python3` it works. It tries to run as a bash script otherwise.
 
After looking at the code, I'd recommend just fallowing the steps on the projects this one depends on. After some time and practice, I'm sure this application will be good.  

Everyone has to start somewhere of course and the interface looks nice. Maybe it'll be what they want in the future.
